{% set name = "mox" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 424ee725ee12652802b4e86571f816059b0d392401ceae70bf6487d65602cba9

build:
  number: 1
  skip: true  # [py3k]
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - mox

about:
  home: http://code.google.com/p/pymox/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: Mock object framework
  description: |
    Mox is a mock object framework for Python based on the Java mock
    object framework EasyMock.

extra:
  recipe-maintainers:
    - jakirkham
